export const Actions = {
    GET_DATA: 'GET_DATA',
    CHANGE_VISIBILITY_MENU: 'CHANGE_VISIBILITY_MENU',
    CHANGE_TARGET: 'CHANGE_TARGET',
    CHANGE_COST: 'CHANGE_COST',
    CHANGE_FEE: 'CHANGE_FEE',
    CHANGE_PERIOD: 'CHANGE_PERIOD',
    CHANGE_USE_CAPITAL: 'CHANGE_USE_CAPITAL'
};

export const Tabs = {
    DEPOSITS: 'DEPOSITS',
    CREDITS: 'CREDITS',
    INSURANCE: 'INSURANCE',
    ONLINE_SERVICES: 'ONLINE_SERVICES'
};

export const TabNames = {
    DEPOSITS: 'Вклады',
    CREDITS: 'Кредиты',
    INSURANCE: 'Страхование',
    ONLINE_SERVICES: 'Онлайн-сервисы'
};
